/* P0 — the QR wrapper around the vendored Nayuki encoder.
 *
 * These four assertions are about web/js/qr.js, never about
 * web/js/qrcodegen.js. Finder patterns, timing lines and determinism are
 * the vendored encoder's business and the golden matrix proves them
 * transitively; asserting them here would only restate upstream's own
 * test suite in a place we have to maintain.
 *
 * The golden itself is deliberately NOT generated by the module under
 * test. testdata/qr-golden.txt comes from Nayuki's independent C port
 * (c/qrcodegen.c) driven over testdata/qr-golden-link.txt. The risk this
 * plan named is translation risk — the TypeScript port ships no tests of
 * its own, they live in c/qrcodegen-test.c — so the oracle has to be the
 * other implementation, or it proves nothing.
 *
 * That is also why the link still names my.scimux.eu, the origin scimux
 * used before 2026-09-12. The link is frozen payload, not a claim about
 * where the rendezvous lives: the matrix beside it was produced from
 * these exact bytes, so substituting a new name here without re-running
 * the C port would assert a matrix nothing ever computed. Both files
 * move together or neither does.
 */
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { qrMatrix, qrSVG } from "../js/qr.js";

const here = dirname(fileURLToPath(import.meta.url));
const goldenLink = readFileSync(join(here, "testdata", "qr-golden-link.txt"), "utf8").trim();
const goldenRows = readFileSync(join(here, "testdata", "qr-golden.txt"), "utf8")
  .split("\n")
  .filter((line) => line.length > 0);
const goldenSize = Number(goldenRows[0]);
const goldenMatrix = goldenRows.slice(1);

test("qrMatrix reproduces the C reference port's matrix for a representative pairing link", () => {
  const m = qrMatrix(goldenLink);
  assert.equal(m.size, goldenSize, "module count differs from the C reference");
  const got = [];
  for (let y = 0; y < m.size; y++) {
    let row = "";
    for (let x = 0; x < m.size; x++) row += m.get(x, y) ? "1" : "0";
    got.push(row);
  }
  assert.deepEqual(got, goldenMatrix, "matrix differs from the C reference port");
});

test("a deployed-origin pairing link lands on version 10 (57 modules)", () => {
  /* Not a global invariant: qrMatrix picks the version from the payload,
   * and a longer rendezvous origin legitimately spills to version 11.
   * This pins the size for THIS fixture, so a re-vendor that silently
   * changed version selection is visible. */
  assert.equal(qrMatrix(goldenLink).size, 57);
});

test("qrSVG surrounds the symbol with the 4-module quiet zone the spec requires", () => {
  const m = qrMatrix(goldenLink);
  const svg = qrSVG(m);
  const span = m.size + 8;
  assert.match(svg, new RegExp(`viewBox="0 0 ${span} ${span}"`), "viewBox does not allow for a 4-module border on each side");
  assert.match(svg, /\bd="M4,4/, "the first dark module is not offset by the quiet zone");
});

test("qrSVG paints explicit colours, never currentColor", () => {
  /* A scanner reads reflectance, not CSS. Inheriting the page's colour
   * is how a QR silently stops working in dark mode. */
  const svg = qrSVG(qrMatrix(goldenLink));
  assert.doesNotMatch(svg, /currentColor/i, "modules inherit the page colour");
  assert.match(svg, /fill="#[0-9a-fA-F]{3,6}"[^>]*\/>[\s\S]*fill="#[0-9a-fA-F]{3,6}"/, "background and foreground are not both explicitly filled");
});
